version: 2
updates:
  - package-ecosystem: "gradle"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      libs:
        patterns:
          - "*"
    open-pull-requests-limit: 1
    ignore:
      - dependency-name: "id.walt.mdoc-credentials:waltid-mdoc-credentials-jvm"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    groups:
      actions:
        patterns:
          - "*"
    open-pull-requests-limit: 1
