version: '3.3'

services:
  verifier:
    image: ghcr.io/niscy-eudiw/eudi-srv-web-verifier-endpoint-23220-4-kt:v0.1.0
    container_name: verifier-backend
    ports:
      - "8080:8080"
    environment:
      VERIFIER_PUBLICURL: "https://10.240.174.10"
      VERIFIER_RESPONSE_MODE: "DirectPost"

  verifier-ui:
    image: ghcr.io/niscy-eudiw/eudi-web-verifier:v0.1.0
    container_name: verifier-ui
    ports:
      - "4300:4300"
    environment:
      - DOMAIN_NAME=""
      - HOST_API="https://10.240.174.10"

  haproxy:
    image: haproxy:2.7.2
    container_name: haproxy
    ports:
      - "443:443"
    volumes:
      - ./haproxy.conf:/usr/local/etc/haproxy/haproxy.cfg
      - ./haproxy.pem:/etc/ssl/certs/mysite.pem
